import WallpaperSection from '@/components/WallpaperSection';

export default function MobilePage() {
    return (
        <main className="min-h-screen pt-24 pb-16">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="mb-12 text-center">
                    <h1 className="text-4xl font-bold text-white mb-4">Mobile Wallpapers</h1>
                    <p className="text-white/60 max-w-2xl mx-auto">
                        Premium 9:16 vertical wallpapers optimized for your smartphone.
                        Generated by state-of-the-art AI models.
                    </p>
                </div>

                <div className="space-y-20">
                    <WallpaperSection title="All Mobile Wallpapers" type="vertical" count={12} />
                </div>
            </div>
        </main>
    );
}
