import { Camera, Users, Target, Shield } from 'lucide-react';

export default function AboutPage() {
    return (
        <main className="min-h-screen pt-24 pb-16">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto">
                    <div className="text-center mb-16">
                        <h1 className="text-4xl font-bold text-white mb-6">About theAIclip</h1>
                        <p className="text-white/60 text-lg leading-relaxed">
                            Welcome to the future of digital art. theAIclip is a dedicated platform for high-quality,
                            AI-generated wallpapers tailored for every screen.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-20">
                        <div className="bg-white/5 border border-white/10 rounded-2xl p-8 backdrop-blur-sm">
                            <Target className="text-blue-500 mb-4" size={32} />
                            <h3 className="text-xl font-bold text-white mb-3">Our Mission</h3>
                            <p className="text-white/60 text-sm leading-relaxed">
                                To democratize access to beautiful, unique, and high-quality digital backgrounds
                                generated by state-of-the-art AI technology.
                            </p>
                        </div>
                        <div className="bg-white/5 border border-white/10 rounded-2xl p-8 backdrop-blur-sm">
                            <Shield className="text-purple-500 mb-4" size={32} />
                            <h3 className="text-xl font-bold text-white mb-3">Quality Guaranteed</h3>
                            <p className="text-white/60 text-sm leading-relaxed">
                                Every wallpaper is carefully curated and optimized for various aspect ratios,
                                from your smartphone to your ultra-wide monitor.
                            </p>
                        </div>
                    </div>

                    <div className="text-center space-y-8">
                        <h2 className="text-2xl font-bold text-white">Join Our Community</h2>
                        <p className="text-white/60 max-w-2xl mx-auto">
                            Whether you're an AI enthusiast, a digital artist, or just someone who loves beautiful backgrounds,
                            there's a place for you at theAIclip.
                        </p>
                        <div className="inline-block px-10 py-4 bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl text-white font-bold hover:scale-105 transition-transform cursor-pointer shadow-lg shadow-blue-500/20">
                            Explore Current Trending
                        </div>
                    </div>
                </div>
            </div>
        </main>
    );
}
