import Link from 'next/link';
import { Camera, Facebook, Twitter, Instagram, Youtube, Mail, MapPin, Phone } from 'lucide-react';

export default function Footer() {
    const currentYear = new Date().getFullYear();

    return (
        <footer className="mt-20 border-t border-white/10 bg-black/50 backdrop-blur-md pt-16 pb-8">
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="grid grid-cols-1 gap-12 md:grid-cols-2 lg:grid-cols-4">
                    {/* Brand and Description */}
                    <div className="space-y-6">
                        <Link href="/" className="flex items-center space-x-2 transition-opacity hover:opacity-80">
                            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 shadow-lg shadow-blue-500/20">
                                <Camera className="text-white" size={24} />
                            </div>
                            <span className="text-xl font-bold tracking-tight text-white">
                                theAI<span className="text-blue-500">clip</span>
                            </span>
                        </Link>
                        <p className="text-sm leading-relaxed text-white/60">
                            Discover and download premium AI-generated wallpapers. High-quality backgrounds for all your devices, generated by state-of-the-art models.
                        </p>
                        <div className="flex space-x-4">
                            {[Facebook, Twitter, Instagram, Youtube].map((Icon, i) => (
                                <Link
                                    key={i}
                                    href="#"
                                    className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/5 text-white/60 transition-all hover:bg-blue-500 hover:text-white"
                                >
                                    <Icon size={20} />
                                </Link>
                            ))}
                        </div>
                    </div>

                    {/* Quick Links */}
                    <div>
                        <h3 className="mb-6 text-sm font-bold uppercase tracking-wider text-white">Quick Links</h3>
                        <ul className="space-y-4">
                            {['Home', 'About Us', 'Contact', 'Blog', 'Terms of Service'].map((item) => (
                                <li key={item}>
                                    <Link href="#" className="text-sm text-white/60 transition-colors hover:text-blue-400">
                                        {item}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Categories */}
                    <div>
                        <h3 className="mb-6 text-sm font-bold uppercase tracking-wider text-white">Wallpapers</h3>
                        <ul className="space-y-4">
                            {['Trending', 'Newest', 'Mobile (9:16)', 'Desktop (16:9)', 'Animated'].map((item) => (
                                <li key={item}>
                                    <Link href="#" className="text-sm text-white/60 transition-colors hover:text-blue-400">
                                        {item}
                                    </Link>
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Newsletter / Contact */}
                    <div>
                        <h3 className="mb-6 text-sm font-bold uppercase tracking-wider text-white">Stay Updated</h3>
                        <p className="mb-6 text-sm text-white/60">Subscribe to our newsletter for the latest AI wallpaper releases.</p>
                        <form className="relative">
                            <input
                                type="email"
                                placeholder="Enter your email"
                                className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none transition-all focus:border-blue-500/50 focus:ring-1 focus:ring-blue-500/50"
                            />
                            <button
                                type="submit"
                                className="absolute right-1 top-1 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white transition-all hover:bg-blue-500"
                            >
                                Send
                            </button>
                        </form>
                        <div className="mt-8 space-y-3">
                            <div className="flex items-center space-x-3 text-sm text-white/60">
                                <Mail size={16} className="text-blue-400" />
                                <span>support@theaiclip.com</span>
                            </div>
                            <div className="flex items-center space-x-3 text-sm text-white/60">
                                <MapPin size={16} className="text-blue-400" />
                                <span>Global Headquaters</span>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Bottom Bar */}
                <div className="mt-16 border-t border-white/10 pt-8 text-center text-sm text-white/40">
                    <p>© {currentYear} theAIclip. All rights reserved. Designed with ❤️ for AI Enthusiasts.</p>
                </div>
            </div>
        </footer>
    );
}
