import { Search } from 'lucide-react';

export default function Hero() {
    return (
        <section className="relative w-full h-[70vh] flex flex-col items-center justify-center overflow-hidden">
            {/* Background Image with Overlay */}
            <div
                className="absolute inset-0 bg-cover bg-center bg-no-repeat transition-transform duration-1000 hover:scale-105"
                style={{
                    backgroundImage: `url('https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop')`,
                }}
            />
            <div className="absolute inset-0 bg-black/50 backdrop-blur-[2px]" />

            {/* Content */}
            <div className="relative z-10 w-full max-w-3xl px-6 text-center space-y-8">
                <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tighter drop-shadow-2xl">
                    AI DREAM <span className="text-blue-500">NEST</span>
                </h1>
                <p className="text-lg md:text-xl text-gray-200 max-w-xl mx-auto font-medium">
                    Discover thousands of vertical and desktop wallpapers generated by advanced AI.
                </p>

                {/* Search Bar */}
                <div className="glass flex items-center p-2 mt-8 transition-all duration-300 focus-within:ring-2 focus-within:ring-blue-500/50">
                    <Search className="ml-4 text-gray-400" size={24} />
                    <input
                        type="text"
                        placeholder="Search for wallpapers (e.g. Cyberpunk, Nature, Minimalist)..."
                        className="flex-1 bg-transparent border-none outline-none px-4 py-3 text-white placeholder:text-gray-500 text-lg"
                    />
                    <button className="bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-lg font-bold transition-all duration-200 shadow-lg active:scale-95">
                        Search
                    </button>
                </div>
            </div>
        </section>
    );
}
